CREATE DATABASE tienda;
use tienda;

create TABLE trabajadores
(
ID_trabajador INT  PRIMARY KEY,
NOMBRE VARCHAR (50) NOT NULL,
A_PATERNO VARCHAR(20) NOT NULL,
A_MATERNO VARCHAR(20) NOT NULL,
DIRECCION VARCHAR(255) NOT NULL,
TELEFONO VARCHAR(10)
);

CREATE TABLE clientes
(
ID_cliente INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(255) NOT NULL,
TELEFONO VARCHAR(10)
);

CREATE TABLE prestamo
(
ID_prestamo INT IDENTITY(1,1) PRIMARY KEY,
CLIENTE INT FOREIGN KEY REFERENCES clientes(ID_cliente),
TOTAL FLOAT NOT NULL,
);

CREATE TABLE limpieza_personal
(
ID_lim_personal INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_LIM_PERSONAL VARCHAR(50) NOT NULL,
PRECIO FLOAT,
CANTIDAD INT
);

CREATE TABLE limpieza_hogar
(
ID_lim_hogar INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_LIM_HOGAR VARCHAR(50) NOT NULL,
PRECIO FLOAT,
CANTIDAD INT
);

CREATE TABLE herramienta
(
ID_herramineta INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_HERRAMIENTA VARCHAR(50) NOT NULL,
PRECIO FLOAT,
CANTIDAD INT
);

CREATE TABLE jarceria
(
ID_jarceria INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_JARCERIA VARCHAR(50) NOT NULL,
PRECIO FLOAT,
CANTIDAD INT
);

CREATE TABLE comestible
(
ID_comestible INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_COMESTIBLE VARCHAR(50) NOT NULL,
PRECIO FLOAT,
CANTIDAD INT
);

CREATE TABLE bebibles
(
ID_bebibles INT  PRIMARY KEY,
NOMBRE_BEBIBLES VARCHAR(50) NOT NULL,
PRECIO FLOAT,
CANTIDAD INT
);

INSERT INTO trabajadores (NOMBRE,A_PATERNO,A_MATERNO,DIRECCION,TELEFONO) 
VALUES ('KARLA','HERNANDEZ','ARCOS','PETUNIA 789','5510121314'), ('BELEN','ROSALES','NOGUES','PALQUI 650','5520212324'), ('NATALIA','DIONICIO','FRANCO','TUNA 10','5530313234'), ('DAVID','HERNANDEZ','RODRIGUEZ','PLATANO 296','5540414243'), ('GERARDO','GUTIERREZ','LOPEZ','CLAVEL 100','5550515253');

INSERT INTO  clientes (NOMBRE, DIRECCION, TELEFONO) 
VALUES ('ANAYANSI', 'PALQUI 600','5500000001'), ('NATALY', 'PALQUI 601','5500000002'), ('FERNANDA', 'PALQUI 602','5500000003'), ('ARMANDO', 'PALQUI 603','5500000004'), ('OSCAR', 'PALQUI 604','5500000005');

INSERT INTO prestamo (CLIENTE,TOTAL)
VALUES ('2','33'), ('4', '52'), ('1','10'), ('5', '80'), ('3', '63');

INSERT INTO bebibles (ID_bebibles,NOMBRE_BEBIBLES,CANTIDAD, PRECIO) 
VALUES ('1','COCA COLA 600','100','14'), ('2','PEPSI 600', '50', '13'), ('3','BONAFINA 1LT', '20','20'), ('4','SPRITE 600', '10', '13'), ('5','SIDRAL 1LT', '6', '13');

INSERT INTO comestible (NOMBRE_COMESTIBLE,CANTIDAD, PRECIO) 
VALUES ('SABRITAS','100','13'), ('FRIJOLES', '3', '16'), ('CHILES', '7','11'), ('CHICLES', '100', '1'), ('DORITOS', '20', '12');

INSERT INTO herramienta (NOMBRE_HERRAMIENTA,CANTIDAD, PRECIO) 
VALUES ('MARTILLO','3','80'), ('TALADRO', '2', '1500'), ('PIJAS', '200','1.50'), ('BROCAS', '1', '30'), ('PAQUETE DE DESARMADORES', '2', '100');

INSERT INTO jarceria (NOMBRE_JARCERIA,CANTIDAD, PRECIO) 
VALUES ('ATOMIZADOR','5','30'), ('ESCOBAS', '10', '20'), ('JALADORES', '3','20'), ('RECOGEDOR', '2', '25'), ('TRAPOS PARA LIMPIAR', '50', '9');

INSERT INTO limpieza_hogar (NOMBRE_LIM_HOGAR,CANTIDAD, PRECIO) 
VALUES ('CLORO 1LT','5','13'), ('FABULOSO MORADO', '10', '22'), ('FABULOSO AMARILLO', '3','22'), ('FABULOSO AZUL', '2', '22'), ('JABON ROMA 1/4', '20', '10');

INSERT INTO  limpieza_personal (NOMBRE_LIM_PERSONAL,CANTIDAD, PRECIO) 
VALUES ('CEPILLO DE DIENTES','10','12'), ('GEL', '5', '20'), ('CURITAS', '100','1'), ('SHAMPOO', '50', '3'), ('ALCOHOL', '3', '27');


SELECT * FROM bebibles;
SELECT * FROM clientes;
SELECT * FROM comestible;
SELECT * FROM herramienta;
SELECT * FROM limpieza_hogar;
SELECT * FROM limpieza_personal;
SELECT * FROM prestamo;
SELECT * FROM trabajadores;
SELECT * FROM jarceria;

